<a href="https://colab.research.google.com/github/sreejasomavarapu/Machine-Learning/blob/main/knn_decision_tree_logistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **KNN**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('tele.csv')

In [ ]:
X = dataset.drop('custcat',axis='columns')
y = dataset['custcat']

In [ ]:
y

0      1
1      4
2      3
3      1
4      3
      ..
995    1
996    1
997    4
998    3
999    2
Name: custcat, Length: 1000, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [ ]:
len(X_train)

750

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 101)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=101)

In [ ]:
knn.score(X_test, y_test)

0.408

In [ ]:
knn.score(X_train, y_train)

0.3626666666666667

In [ ]:
y_pred = knn.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm



array([[45, 10, 16,  1],
       [13, 18, 21,  4],
       [22, 10, 32,  5],
       [16, 11, 19,  7]])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
print("Precision: ",precision_score(y_test,y_pred,average='macro'))
print("Accuracy: ",accuracy_score(y_test,y_pred))
print("Recall: ",recall_score(y_test,y_pred,average='macro'))

Precision:  0.4028745020735567
Accuracy:  0.408
Recall:  0.3855680397671784


# **Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy')
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
classifier.score(X_test,y_test)

0.32

In [ ]:
y_pred_dt = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
cm = confusion_matrix(y_test, y_pred_dt)
cm


array([[27, 12, 22, 11],
       [12, 14, 17, 13],
       [13, 19, 22, 15],
       [ 6, 17, 13, 17]])

In [ ]:
print("Precision: ",precision_score(y_test,y_pred_dt,average='macro'))
print("Accuracy: ",accuracy_score(y_test,y_pred_dt))
print("Recall: ",recall_score(y_test,y_pred_dt,average='macro'))

Precision:  0.3230481047152349
Accuracy:  0.32
Recall:  0.31614882417281925


# **Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(random_state=0)# penalty='l2',
logreg.fit(X_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [ ]:
y_pred_lr = logreg.predict(X_test)

In [ ]:
logreg.score(X_test,y_test)

0.408

In [ ]:
cm = confusion_matrix(y_test, y_pred_lr)
cm

array([[34,  7, 21, 10],
       [ 8, 13, 18, 17],
       [17, 14, 29,  9],
       [ 7, 12,  8, 26]])

In [ ]:
print("Precision: ",precision_score(y_test,y_pred_lr,average='macro'))
print("Accuracy: ",accuracy_score(y_test,y_pred_lr))
print("Recall: ",recall_score(y_test,y_pred_lr,average='macro'))

Precision:  0.39967349922044687
Accuracy:  0.408
Recall:  0.403805243043348
